# coding: utf-8

"""
    Vault Ninja — Organization SDK API

    Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vault_ninja.models.secret import Secret

class TestSecret(unittest.TestCase):
    """Secret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Secret:
        """Test Secret
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Secret`
        """
        model = Secret()
        if include_optional:
            return Secret(
                id = '',
                title = '',
                description = '',
                tags = [
                    ''
                    ],
                org_id = '',
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fields = [
                    {id=3fa85f64-5717-4562-b3fc-2c963f66afa6, secret_id=1fa85f64-5717-4562-b3fc-2c963f66afa6, position=0, field_type=password, label=Password, value=hunter2, created_at=2026-01-01T00:00:00Z}
                    ],
                files = [
                    vault_ninja.models.secret_file.SecretFile(
                        id = '', 
                        secret_id = '', 
                        original_name = '', 
                        content_type = '', 
                        size_bytes = 56, 
                        position = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        url = '', )
                    ]
            )
        else:
            return Secret(
                id = '',
                title = '',
                description = '',
                tags = [
                    ''
                    ],
                org_id = '',
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fields = [
                    {id=3fa85f64-5717-4562-b3fc-2c963f66afa6, secret_id=1fa85f64-5717-4562-b3fc-2c963f66afa6, position=0, field_type=password, label=Password, value=hunter2, created_at=2026-01-01T00:00:00Z}
                    ],
                files = [
                    vault_ninja.models.secret_file.SecretFile(
                        id = '', 
                        secret_id = '', 
                        original_name = '', 
                        content_type = '', 
                        size_bytes = 56, 
                        position = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        url = '', )
                    ],
        )
        """

    def testSecret(self):
        """Test Secret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
