# coding: utf-8

"""
    Vault Ninja — Organization SDK API

    Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vault_ninja.api.secrets_api import SecretsApi


class TestSecretsApi(unittest.TestCase):
    """SecretsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecretsApi()

    def tearDown(self) -> None:
        pass

    def test_get_field(self) -> None:
        """Test case for get_field

        Get a single decrypted field by ID
        """
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        Download a file by ID
        """
        pass

    def test_get_secret(self) -> None:
        """Test case for get_secret

        Get secret with all decrypted fields and file metadata
        """
        pass

    def test_list_secrets(self) -> None:
        """Test case for list_secrets

        List org secrets
        """
        pass


if __name__ == '__main__':
    unittest.main()
