# coding: utf-8

# flake8: noqa

"""
    Vault Ninja — Organization SDK API

    Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "VaultNinjaClient",
    "SecretsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Error",
    "FieldType",
    "Secret",
    "SecretField",
    "SecretFile",
    "SecretSummary",
]

# import apis into sdk package
from vault_ninja.api.secrets_api import SecretsApi as SecretsApi

# import ApiClient
from vault_ninja.api_response import ApiResponse as ApiResponse
from vault_ninja.api_client import ApiClient as ApiClient
from vault_ninja.configuration import Configuration as Configuration
from vault_ninja.exceptions import OpenApiException as OpenApiException
from vault_ninja.exceptions import ApiTypeError as ApiTypeError
from vault_ninja.exceptions import ApiValueError as ApiValueError
from vault_ninja.exceptions import ApiKeyError as ApiKeyError
from vault_ninja.exceptions import ApiAttributeError as ApiAttributeError
from vault_ninja.exceptions import ApiException as ApiException

# import models into sdk package
from vault_ninja.models.error import Error as Error
from vault_ninja.models.field_type import FieldType as FieldType
from vault_ninja.models.secret import Secret as Secret
from vault_ninja.models.secret_field import SecretField as SecretField
from vault_ninja.models.secret_file import SecretFile as SecretFile
from vault_ninja.models.secret_summary import SecretSummary as SecretSummary

# import handwritten client
from vault_ninja.client import VaultNinjaClient as VaultNinjaClient

