/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ninja — Organization SDK API
 * Read-only API for programmatic access to an organization\'s secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FieldType = {
    Password: 'password',
    Card: 'card',
    Totp: 'totp',
    Url: 'url',
    Note: 'note',
    Text: 'text'
} as const;
export type FieldType = typeof FieldType[keyof typeof FieldType];


export function instanceOfFieldType(value: any): boolean {
    for (const key in FieldType) {
        if (Object.prototype.hasOwnProperty.call(FieldType, key)) {
            if (FieldType[key as keyof typeof FieldType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FieldTypeFromJSON(json: any): FieldType {
    return FieldTypeFromJSONTyped(json, false);
}

export function FieldTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldType {
    return json as FieldType;
}

export function FieldTypeToJSON(value?: FieldType | null): any {
    return value as any;
}

export function FieldTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FieldType {
    return value as FieldType;
}

