/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ninja — Organization SDK API
 * Read-only API for programmatic access to an organization\'s secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldType } from './FieldType';
import {
    FieldTypeFromJSON,
    FieldTypeFromJSONTyped,
    FieldTypeToJSON,
    FieldTypeToJSONTyped,
} from './FieldType';

/**
 * A single field belonging to a secret. The `value` is returned decrypted.
 * @export
 * @interface SecretField
 */
export interface SecretField {
    /**
     * 
     * @type {string}
     * @memberof SecretField
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SecretField
     */
    secretId: string;
    /**
     * 
     * @type {number}
     * @memberof SecretField
     */
    position: number;
    /**
     * 
     * @type {FieldType}
     * @memberof SecretField
     */
    fieldType: FieldType;
    /**
     * 
     * @type {string}
     * @memberof SecretField
     */
    label: string;
    /**
     * Decrypted plaintext value
     * @type {string}
     * @memberof SecretField
     */
    value: string;
    /**
     * 
     * @type {Date}
     * @memberof SecretField
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the SecretField interface.
 */
export function instanceOfSecretField(value: object): value is SecretField {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('secretId' in value) || value['secretId'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('fieldType' in value) || value['fieldType'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SecretFieldFromJSON(json: any): SecretField {
    return SecretFieldFromJSONTyped(json, false);
}

export function SecretFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretField {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'secretId': json['secret_id'],
        'position': json['position'],
        'fieldType': FieldTypeFromJSON(json['field_type']),
        'label': json['label'],
        'value': json['value'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function SecretFieldToJSON(json: any): SecretField {
    return SecretFieldToJSONTyped(json, false);
}

export function SecretFieldToJSONTyped(value?: SecretField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'secret_id': value['secretId'],
        'position': value['position'],
        'field_type': FieldTypeToJSON(value['fieldType']),
        'label': value['label'],
        'value': value['value'],
        'created_at': value['createdAt'].toISOString(),
    };
}

