/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ninja — Organization SDK API
 * Read-only API for programmatic access to an organization\'s secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lightweight secret listing — no fields or files.
 * @export
 * @interface SecretSummary
 */
export interface SecretSummary {
    /**
     * 
     * @type {string}
     * @memberof SecretSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SecretSummary
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SecretSummary
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SecretSummary
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SecretSummary
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof SecretSummary
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof SecretSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SecretSummary
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SecretSummary interface.
 */
export function instanceOfSecretSummary(value: object): value is SecretSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SecretSummaryFromJSON(json: any): SecretSummary {
    return SecretSummaryFromJSONTyped(json, false);
}

export function SecretSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
        'orgId': json['org_id'],
        'createdBy': json['created_by'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SecretSummaryToJSON(json: any): SecretSummary {
    return SecretSummaryToJSONTyped(json, false);
}

export function SecretSummaryToJSONTyped(value?: SecretSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
        'org_id': value['orgId'],
        'created_by': value['createdBy'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

