/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ninja — Organization SDK API
 * Read-only API for programmatic access to an organization\'s secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretField } from './SecretField';
import {
    SecretFieldFromJSON,
    SecretFieldFromJSONTyped,
    SecretFieldToJSON,
    SecretFieldToJSONTyped,
} from './SecretField';
import type { SecretFile } from './SecretFile';
import {
    SecretFileFromJSON,
    SecretFileFromJSONTyped,
    SecretFileToJSON,
    SecretFileToJSONTyped,
} from './SecretFile';

/**
 * A secret with all its decrypted fields and file metadata.
 * Secrets are always scoped to the org that owns the API key.
 * 
 * @export
 * @interface Secret
 */
export interface Secret {
    /**
     * 
     * @type {string}
     * @memberof Secret
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Secret
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Secret
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Secret
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Secret
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof Secret
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Secret
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Secret
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<SecretField>}
     * @memberof Secret
     */
    fields: Array<SecretField>;
    /**
     * 
     * @type {Array<SecretFile>}
     * @memberof Secret
     */
    files: Array<SecretFile>;
}

/**
 * Check if a given object implements the Secret interface.
 */
export function instanceOfSecret(value: object): value is Secret {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function SecretFromJSON(json: any): Secret {
    return SecretFromJSONTyped(json, false);
}

export function SecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): Secret {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
        'orgId': json['org_id'],
        'createdBy': json['created_by'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'fields': ((json['fields'] as Array<any>).map(SecretFieldFromJSON)),
        'files': ((json['files'] as Array<any>).map(SecretFileFromJSON)),
    };
}

export function SecretToJSON(json: any): Secret {
    return SecretToJSONTyped(json, false);
}

export function SecretToJSONTyped(value?: Secret | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
        'org_id': value['orgId'],
        'created_by': value['createdBy'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'fields': ((value['fields'] as Array<any>).map(SecretFieldToJSON)),
        'files': ((value['files'] as Array<any>).map(SecretFileToJSON)),
    };
}

