/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ninja — Organization SDK API
 * Read-only API for programmatic access to an organization\'s secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata for a file attached to a secret.
 * Use the `url` field to download the file contents — it points to
 * `GET /secrets/{secretId}/files/{fileId}`.
 * 
 * @export
 * @interface SecretFile
 */
export interface SecretFile {
    /**
     * 
     * @type {string}
     * @memberof SecretFile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SecretFile
     */
    secretId: string;
    /**
     * 
     * @type {string}
     * @memberof SecretFile
     */
    originalName: string;
    /**
     * 
     * @type {string}
     * @memberof SecretFile
     */
    contentType: string;
    /**
     * 
     * @type {number}
     * @memberof SecretFile
     */
    sizeBytes: number;
    /**
     * 
     * @type {number}
     * @memberof SecretFile
     */
    position: number;
    /**
     * 
     * @type {Date}
     * @memberof SecretFile
     */
    createdAt: Date;
    /**
     * SDK download URL for this file
     * @type {string}
     * @memberof SecretFile
     */
    url: string;
}

/**
 * Check if a given object implements the SecretFile interface.
 */
export function instanceOfSecretFile(value: object): value is SecretFile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('secretId' in value) || value['secretId'] === undefined) return false;
    if (!('originalName' in value) || value['originalName'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function SecretFileFromJSON(json: any): SecretFile {
    return SecretFileFromJSONTyped(json, false);
}

export function SecretFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretFile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'secretId': json['secret_id'],
        'originalName': json['original_name'],
        'contentType': json['content_type'],
        'sizeBytes': json['size_bytes'],
        'position': json['position'],
        'createdAt': (new Date(json['created_at'])),
        'url': json['url'],
    };
}

export function SecretFileToJSON(json: any): SecretFile {
    return SecretFileToJSONTyped(json, false);
}

export function SecretFileToJSONTyped(value?: SecretFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'secret_id': value['secretId'],
        'original_name': value['originalName'],
        'content_type': value['contentType'],
        'size_bytes': value['sizeBytes'],
        'position': value['position'],
        'created_at': value['createdAt'].toISOString(),
        'url': value['url'],
    };
}

