# coding: utf-8

# flake8: noqa
"""
    Vault Ninja — Organization SDK API

    Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from vault_ninja.models.error import Error
from vault_ninja.models.field_type import FieldType
from vault_ninja.models.secret import Secret
from vault_ninja.models.secret_field import SecretField
from vault_ninja.models.secret_file import SecretFile
from vault_ninja.models.secret_summary import SecretSummary

