# coding: utf-8

"""
    Vault Ninja — Organization SDK API

    Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FieldType(str, Enum):
    """
    FieldType
    """

    """
    allowed enum values
    """
    PASSWORD = 'password'
    CARD = 'card'
    TOTP = 'totp'
    URL = 'url'
    NOTE = 'note'
    TEXT = 'text'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FieldType from a JSON string"""
        return cls(json.loads(json_str))


