/*
Vault Ninja — Organization SDK API

Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vaultninja

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SecretField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretField{}

// SecretField A single field belonging to a secret. The `value` is returned decrypted.
type SecretField struct {
	Id string `json:"id"`
	SecretId string `json:"secret_id"`
	Position int32 `json:"position"`
	FieldType FieldType `json:"field_type"`
	Label string `json:"label"`
	// Decrypted plaintext value
	Value string `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type _SecretField SecretField

// NewSecretField instantiates a new SecretField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretField(id string, secretId string, position int32, fieldType FieldType, label string, value string, createdAt time.Time) *SecretField {
	this := SecretField{}
	this.Id = id
	this.SecretId = secretId
	this.Position = position
	this.FieldType = fieldType
	this.Label = label
	this.Value = value
	this.CreatedAt = createdAt
	return &this
}

// NewSecretFieldWithDefaults instantiates a new SecretField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretFieldWithDefaults() *SecretField {
	this := SecretField{}
	return &this
}

// GetId returns the Id field value
func (o *SecretField) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretField) SetId(v string) {
	o.Id = v
}

// GetSecretId returns the SecretId field value
func (o *SecretField) GetSecretId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetSecretIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretId, true
}

// SetSecretId sets field value
func (o *SecretField) SetSecretId(v string) {
	o.SecretId = v
}

// GetPosition returns the Position field value
func (o *SecretField) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *SecretField) SetPosition(v int32) {
	o.Position = v
}

// GetFieldType returns the FieldType field value
func (o *SecretField) GetFieldType() FieldType {
	if o == nil {
		var ret FieldType
		return ret
	}

	return o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetFieldTypeOk() (*FieldType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldType, true
}

// SetFieldType sets field value
func (o *SecretField) SetFieldType(v FieldType) {
	o.FieldType = v
}

// GetLabel returns the Label field value
func (o *SecretField) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *SecretField) SetLabel(v string) {
	o.Label = v
}

// GetValue returns the Value field value
func (o *SecretField) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SecretField) SetValue(v string) {
	o.Value = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SecretField) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SecretField) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SecretField) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o SecretField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["secret_id"] = o.SecretId
	toSerialize["position"] = o.Position
	toSerialize["field_type"] = o.FieldType
	toSerialize["label"] = o.Label
	toSerialize["value"] = o.Value
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *SecretField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"secret_id",
		"position",
		"field_type",
		"label",
		"value",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretField := _SecretField{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretField)

	if err != nil {
		return err
	}

	*o = SecretField(varSecretField)

	return err
}

type NullableSecretField struct {
	value *SecretField
	isSet bool
}

func (v NullableSecretField) Get() *SecretField {
	return v.value
}

func (v *NullableSecretField) Set(val *SecretField) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretField) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretField(val *SecretField) *NullableSecretField {
	return &NullableSecretField{value: val, isSet: true}
}

func (v NullableSecretField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


