/*
Vault Ninja — Organization SDK API

Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vaultninja

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SecretFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretFile{}

// SecretFile Metadata for a file attached to a secret. Use the `url` field to download the file contents — it points to `GET /secrets/{secretId}/files/{fileId}`. 
type SecretFile struct {
	Id string `json:"id"`
	SecretId string `json:"secret_id"`
	OriginalName string `json:"original_name"`
	ContentType string `json:"content_type"`
	SizeBytes int64 `json:"size_bytes"`
	Position int32 `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	// SDK download URL for this file
	Url string `json:"url"`
}

type _SecretFile SecretFile

// NewSecretFile instantiates a new SecretFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretFile(id string, secretId string, originalName string, contentType string, sizeBytes int64, position int32, createdAt time.Time, url string) *SecretFile {
	this := SecretFile{}
	this.Id = id
	this.SecretId = secretId
	this.OriginalName = originalName
	this.ContentType = contentType
	this.SizeBytes = sizeBytes
	this.Position = position
	this.CreatedAt = createdAt
	this.Url = url
	return &this
}

// NewSecretFileWithDefaults instantiates a new SecretFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretFileWithDefaults() *SecretFile {
	this := SecretFile{}
	return &this
}

// GetId returns the Id field value
func (o *SecretFile) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretFile) SetId(v string) {
	o.Id = v
}

// GetSecretId returns the SecretId field value
func (o *SecretFile) GetSecretId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetSecretIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretId, true
}

// SetSecretId sets field value
func (o *SecretFile) SetSecretId(v string) {
	o.SecretId = v
}

// GetOriginalName returns the OriginalName field value
func (o *SecretFile) GetOriginalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginalName
}

// GetOriginalNameOk returns a tuple with the OriginalName field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetOriginalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalName, true
}

// SetOriginalName sets field value
func (o *SecretFile) SetOriginalName(v string) {
	o.OriginalName = v
}

// GetContentType returns the ContentType field value
func (o *SecretFile) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *SecretFile) SetContentType(v string) {
	o.ContentType = v
}

// GetSizeBytes returns the SizeBytes field value
func (o *SecretFile) GetSizeBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetSizeBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *SecretFile) SetSizeBytes(v int64) {
	o.SizeBytes = v
}

// GetPosition returns the Position field value
func (o *SecretFile) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *SecretFile) SetPosition(v int32) {
	o.Position = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SecretFile) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SecretFile) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUrl returns the Url field value
func (o *SecretFile) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SecretFile) SetUrl(v string) {
	o.Url = v
}

func (o SecretFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["secret_id"] = o.SecretId
	toSerialize["original_name"] = o.OriginalName
	toSerialize["content_type"] = o.ContentType
	toSerialize["size_bytes"] = o.SizeBytes
	toSerialize["position"] = o.Position
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *SecretFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"secret_id",
		"original_name",
		"content_type",
		"size_bytes",
		"position",
		"created_at",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretFile := _SecretFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretFile)

	if err != nil {
		return err
	}

	*o = SecretFile(varSecretFile)

	return err
}

type NullableSecretFile struct {
	value *SecretFile
	isSet bool
}

func (v NullableSecretFile) Get() *SecretFile {
	return v.value
}

func (v *NullableSecretFile) Set(val *SecretFile) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretFile) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretFile(val *SecretFile) *NullableSecretFile {
	return &NullableSecretFile{value: val, isSet: true}
}

func (v NullableSecretFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


