/*
Vault Ninja — Organization SDK API

Read-only API for programmatic access to an organization's secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vaultninja

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SecretSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretSummary{}

// SecretSummary Lightweight secret listing — no fields or files.
type SecretSummary struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Description string `json:"description"`
	Tags []string `json:"tags"`
	OrgId string `json:"org_id"`
	CreatedBy string `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _SecretSummary SecretSummary

// NewSecretSummary instantiates a new SecretSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretSummary(id string, title string, description string, tags []string, orgId string, createdBy string, createdAt time.Time, updatedAt time.Time) *SecretSummary {
	this := SecretSummary{}
	this.Id = id
	this.Title = title
	this.Description = description
	this.Tags = tags
	this.OrgId = orgId
	this.CreatedBy = createdBy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewSecretSummaryWithDefaults instantiates a new SecretSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretSummaryWithDefaults() *SecretSummary {
	this := SecretSummary{}
	return &this
}

// GetId returns the Id field value
func (o *SecretSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretSummary) SetId(v string) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *SecretSummary) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SecretSummary) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value
func (o *SecretSummary) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SecretSummary) SetDescription(v string) {
	o.Description = v
}

// GetTags returns the Tags field value
func (o *SecretSummary) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *SecretSummary) SetTags(v []string) {
	o.Tags = v
}

// GetOrgId returns the OrgId field value
func (o *SecretSummary) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *SecretSummary) SetOrgId(v string) {
	o.OrgId = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *SecretSummary) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *SecretSummary) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SecretSummary) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SecretSummary) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SecretSummary) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SecretSummary) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SecretSummary) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SecretSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["description"] = o.Description
	toSerialize["tags"] = o.Tags
	toSerialize["org_id"] = o.OrgId
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *SecretSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
		"description",
		"tags",
		"org_id",
		"created_by",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretSummary := _SecretSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretSummary)

	if err != nil {
		return err
	}

	*o = SecretSummary(varSecretSummary)

	return err
}

type NullableSecretSummary struct {
	value *SecretSummary
	isSet bool
}

func (v NullableSecretSummary) Get() *SecretSummary {
	return v.value
}

func (v *NullableSecretSummary) Set(val *SecretSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretSummary(val *SecretSummary) *NullableSecretSummary {
	return &NullableSecretSummary{value: val, isSet: true}
}

func (v NullableSecretSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


