/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ninja — Organization SDK API
 * Read-only API for programmatic access to an organization\'s secrets.  ## Authentication All requests must include an `Authorization` header with a Bearer API key: ``` Authorization: Bearer vn_org_<key> ``` API keys are created and managed in your org settings → API Keys. Keys are scoped to a single organization and provide read-only access.  ## Key format Keys start with `vn_org_` followed by 32 random hex characters.  ## Rate limiting Requests are subject to standard rate limiting. Include exponential backoff on `429` responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Secret,
  SecretField,
  SecretSummary,
} from '../models/index';
import {
    SecretFromJSON,
    SecretToJSON,
    SecretFieldFromJSON,
    SecretFieldToJSON,
    SecretSummaryFromJSON,
    SecretSummaryToJSON,
} from '../models/index';

export interface GetFieldRequest {
    id: string;
    fid: string;
}

export interface GetFileRequest {
    id: string;
    fid: string;
}

export interface GetSecretRequest {
    id: string;
}

/**
 * 
 */
export class SecretsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getField without sending the request
     */
    async getFieldRequestOpts(requestParameters: GetFieldRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getField().'
            );
        }

        if (requestParameters['fid'] == null) {
            throw new runtime.RequiredError(
                'fid',
                'Required parameter "fid" was null or undefined when calling getField().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/secrets/{id}/fields/{fid}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"fid"}}`, encodeURIComponent(String(requestParameters['fid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one field with its decrypted value. Useful when you only need a specific credential without fetching the entire secret (e.g. injecting a password into a CI environment). 
     * Get a single decrypted field by ID
     */
    async getFieldRaw(requestParameters: GetFieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecretField>> {
        const requestOptions = await this.getFieldRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecretFieldFromJSON(jsonValue));
    }

    /**
     * Returns one field with its decrypted value. Useful when you only need a specific credential without fetching the entire secret (e.g. injecting a password into a CI environment). 
     * Get a single decrypted field by ID
     */
    async getField(requestParameters: GetFieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecretField> {
        const response = await this.getFieldRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFile without sending the request
     */
    async getFileRequestOpts(requestParameters: GetFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFile().'
            );
        }

        if (requestParameters['fid'] == null) {
            throw new runtime.RequiredError(
                'fid',
                'Required parameter "fid" was null or undefined when calling getFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/secrets/{id}/files/{fid}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"fid"}}`, encodeURIComponent(String(requestParameters['fid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Streams the raw file bytes. Use the `Content-Disposition` header to determine the suggested filename. The `Content-Type` header reflects the original file\'s MIME type. 
     * Download a file by ID
     */
    async getFileRaw(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Streams the raw file bytes. Use the `Content-Disposition` header to determine the suggested filename. The `Content-Type` header reflects the original file\'s MIME type. 
     * Download a file by ID
     */
    async getFile(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSecret without sending the request
     */
    async getSecretRequestOpts(requestParameters: GetSecretRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/secrets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the full secret object including: - All fields with their **decrypted** values - All file metadata with SDK download URLs  The secret must belong to the org that owns the API key. 
     * Get secret with all decrypted fields and file metadata
     */
    async getSecretRaw(requestParameters: GetSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Secret>> {
        const requestOptions = await this.getSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecretFromJSON(jsonValue));
    }

    /**
     * Returns the full secret object including: - All fields with their **decrypted** values - All file metadata with SDK download URLs  The secret must belong to the org that owns the API key. 
     * Get secret with all decrypted fields and file metadata
     */
    async getSecret(requestParameters: GetSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Secret> {
        const response = await this.getSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSecrets without sending the request
     */
    async listSecretsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/secrets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all secrets belonging to the org associated with the API key. Fields and files are **not** included in the list — fetch them via `GET /secrets/{id}` or the individual field/file endpoints. 
     * List org secrets
     */
    async listSecretsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SecretSummary>>> {
        const requestOptions = await this.listSecretsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SecretSummaryFromJSON));
    }

    /**
     * Returns all secrets belonging to the org associated with the API key. Fields and files are **not** included in the list — fetch them via `GET /secrets/{id}` or the individual field/file endpoints. 
     * List org secrets
     */
    async listSecrets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SecretSummary>> {
        const response = await this.listSecretsRaw(initOverrides);
        return await response.value();
    }

}
